server.port: 7000

app:
  user-service:
    host: localhost
    port: 7001
  product-service:
    host: localhost
    port: 7002

logging:
  level:
    root: INFO
    com.dotd: DEBUG
---
spring:
  profiles: docker
server:
  port: 8080

app:
  user-service:
    host: user
    port: 8080
  product-service:
    host: product
    port: 8080