server.port: 7002
server.error.include-message: always

logging:
  level:
    root: INFO
    com.dotd: DEBUG
---
spring:
  profiles: docker
server:
  port: 8080
---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dotd_db?serverTimezone=UTC
    username: dotd_admin
    password: Orangemango3434!

    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
      open-in-view: false
      show-sql: true
      hibernate:
        format_sql: true
        ddl-auto: create
    mvc: # swagger 오류 조치
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER
      hiddenmethod: # put, delete 사용
        filter:
          enabled: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

---
## Multipart properties
# Enable multipart uploads
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

# 개발기간 동안 프로젝트 내의 파일을 업로드할 폴더
file:
  upload-dir: ./uploads