server:
  port: 7001

  logging:
    level:
      root: INFO
      com.dotd: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dotd_db?serverTimezone=UTC
    username: dotd_admin
    password: Orangemango3434!

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
  mvc:  # swagger 오류 조치
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    hiddenmethod: # put, delete 사용
      filter:
        enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE